apiVersion: v1
kind: Service
metadata:
  name: hello-world-microprofile
  labels:
    app: hello-world-microprofile
    tier: backend
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hello-world-microprofile